working except for env var not set
Running tool: /Users/f/.nix-profile/bin/go test -timeout 20s -run ^Test_server_List$ github.com/e2b-dev/infra/packages/orchestrator/internal/server

--- FAIL: Test_server_List (0.00s)
    --- FAIL: Test_server_List/should_return_all_sandboxes (0.00s)
panic: Required environment variable "NODE_ID" (Nomad ID of the instance node) is not set. Please set it to a non-empty value. [recovered]
	panic: Required environment variable "NODE_ID" (Nomad ID of the instance node) is not set. Please set it to a non-empty value. [recovered]
	panic: Required environment variable "NODE_ID" (Nomad ID of the instance node) is not set. Please set it to a non-empty value. [recovered]
	panic: Required environment variable "NODE_ID" (Nomad ID of the instance node) is not set. Please set it to a non-empty value.

goroutine 8 [running]:
testing.tRunner.func1.2({0x1036afc80, 0x140002fd350})
	/nix/store/yjqrp3d93mxa2g80j57whyk55xwxgl7r-go-1.23.6/share/go/src/testing/testing.go:1632 +0x1bc
testing.tRunner.func1()
	/nix/store/yjqrp3d93mxa2g80j57whyk55xwxgl7r-go-1.23.6/share/go/src/testing/testing.go:1635 +0x334
panic({0x1036afc80?, 0x140002fd350?})
	/nix/store/yjqrp3d93mxa2g80j57whyk55xwxgl7r-go-1.23.6/share/go/src/runtime/panic.go:785 +0x124
github.com/e2b-dev/infra/packages/orchestrator/internal/consul.init.OnceValue[...].func5.1()
	/nix/store/yjqrp3d93mxa2g80j57whyk55xwxgl7r-go-1.23.6/share/go/src/sync/oncefunc.go:54 +0x78
panic({0x1036afc80?, 0x140002fd350?})
	/nix/store/yjqrp3d93mxa2g80j57whyk55xwxgl7r-go-1.23.6/share/go/src/runtime/panic.go:785 +0x124
github.com/e2b-dev/infra/packages/orchestrator/internal/consul.init.OnceValue[...].func3.1()
	/nix/store/yjqrp3d93mxa2g80j57whyk55xwxgl7r-go-1.23.6/share/go/src/sync/oncefunc.go:54 +0x78
panic({0x1036afc80?, 0x140002fd350?})
	/nix/store/yjqrp3d93mxa2g80j57whyk55xwxgl7r-go-1.23.6/share/go/src/runtime/panic.go:785 +0x124
github.com/e2b-dev/infra/packages/shared/pkg/utils.RequiredEnv({0x10343c574, 0x7}, {0x103457f25, 0x1d})
	/Users/f/infra/packages/shared/pkg/utils/env.go:16 +0x1a8
github.com/e2b-dev/infra/packages/orchestrator/internal/consul.init.func1()
	/Users/f/infra/packages/orchestrator/internal/consul/node.go:13 +0x34
github.com/e2b-dev/infra/packages/orchestrator/internal/consul.init.OnceValue[...].func3()
	/nix/store/yjqrp3d93mxa2g80j57whyk55xwxgl7r-go-1.23.6/share/go/src/sync/oncefunc.go:57 +0x74
sync.(*Once).doSlow(0x104778a68?, 0x14000193f80?)
	/nix/store/yjqrp3d93mxa2g80j57whyk55xwxgl7r-go-1.23.6/share/go/src/sync/once.go:76 +0xf8
sync.(*Once).Do(0x14000187ba8?, 0x10282f264?)
	/nix/store/yjqrp3d93mxa2g80j57whyk55xwxgl7r-go-1.23.6/share/go/src/sync/once.go:67 +0x24
github.com/e2b-dev/infra/packages/orchestrator/internal/consul.init.OnceValue[...].func4()
	/nix/store/yjqrp3d93mxa2g80j57whyk55xwxgl7r-go-1.23.6/share/go/src/sync/oncefunc.go:62 +0x3c
github.com/e2b-dev/infra/packages/orchestrator/internal/consul.init.func2()
	/Users/f/infra/packages/orchestrator/internal/consul/node.go:18 +0x28
github.com/e2b-dev/infra/packages/orchestrator/internal/consul.init.OnceValue[...].func5()
	/nix/store/yjqrp3d93mxa2g80j57whyk55xwxgl7r-go-1.23.6/share/go/src/sync/oncefunc.go:57 +0x74
sync.(*Once).doSlow(0x1037456c0?, 0x14000700008?)
	/nix/store/yjqrp3d93mxa2g80j57whyk55xwxgl7r-go-1.23.6/share/go/src/sync/once.go:76 +0xf8
sync.(*Once).Do(0x14000187cd8?, 0x1034337a0?)
	/nix/store/yjqrp3d93mxa2g80j57whyk55xwxgl7r-go-1.23.6/share/go/src/sync/once.go:67 +0x24
github.com/e2b-dev/infra/packages/orchestrator/internal/consul.init.OnceValue[...].func6()
	/nix/store/yjqrp3d93mxa2g80j57whyk55xwxgl7r-go-1.23.6/share/go/src/sync/oncefunc.go:62 +0x3c
github.com/e2b-dev/infra/packages/orchestrator/internal/server.(*server).List(0x14000187ef0, {0x103a27770?, 0x1045e7a40?}, 0x1039ffb88?)
	/Users/f/infra/packages/orchestrator/internal/server/sandboxes.go:136 +0x17c
github.com/e2b-dev/infra/packages/orchestrator/internal/server.Test_server_List.func1(0x140001ad380)
	/Users/f/infra/packages/orchestrator/internal/server/sandboxes_test.go:60 +0x210
testing.tRunner(0x140001ad380, 0x14000115800)
	/nix/store/yjqrp3d93mxa2g80j57whyk55xwxgl7r-go-1.23.6/share/go/src/testing/testing.go:1690 +0xe4
created by testing.(*T).Run in goroutine 7
	/nix/store/yjqrp3d93mxa2g80j57whyk55xwxgl7r-go-1.23.6/share/go/src/testing/testing.go:1743 +0x314
FAIL	github.com/e2b-dev/infra/packages/orchestrator/internal/server	0.331s
FAIL